### ISSUE TITLE
NodeJS curl.lib.js "Cannot read property 'context' of undefined"`

### ISSUE THREAD

**Issue by kryo2k** [iotaledger/curl.lib.js#23]
Hello. Trying to use this in NodeJS (v7.10.0).

Package.json:
```json
{
  "dependencies": {
    "curl.lib.js": "^1.0.22",
    "iota.lib.js": "^0.4.6"
  }
}
```

Test code to reproduce issue:
```javascript
const
Iota = require('iota.lib.js'),
curl = require('curl.lib.js');

const iota = new Iota({ ... });
curl.overrideAttachToTangle(iota.api);

// hidden unrelated code to check if node is sync'd

const privateSeed = '...', depth = 8, weight = 14;
const transactions = [ { address: '...', value: 0, tag: '...', message: '...' } ];

iota.api.sendTransfer(privateSeed, depth, weight, transactions, (err, response) =>{
  if(err) {
    console.error(err); // error gets thrown here:
    /*
    TypeError: Cannot read property 'context' of undefined
        at Object.search (~/node_modules/curl.lib.js/src/pearldiver.js:44:15)
        at pow (~/node_modules/curl.lib.js/src/curl.lib.js:19:31)
        at ~/node_modules/curl.lib.js/src/curl.lib.js:59:9
        at doWork (~/node_modules/curl.lib.js/src/curl.lib.js:52:14)
        at doNext (~/node_modules/curl.lib.js/src/curl.lib.js:69:9)
        at api.attachToTangle (~/node_modules/curl.lib.js/src/curl.lib.js:82:5)
        at ~/node_modules/iota.lib.js/lib/api/api.js:527:14
        at makeRequest.prepareResult (~/node_modules/iota.lib.js/lib/utils/makeRequest.js:313:12)
        at exports.XMLHttpRequest.request.onreadystatechange (~/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
        at exports.XMLHttpRequest.dispatchEvent (~/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    */
    return;
  }

  // ....
});
```

After tracking the problem down a little further,  in `node_modules/curl.lib.js/src/pearldiver.js` I see:

```javascript
const search = (instance, states, minWeight) =>{
  if(!instance.context) { ////// <-- this is line 44
    Promise.reject(new Error("Webgl2 Is not Available"));
  }
}
```

I'll follow-up if I find out anything new.

**Comment by kryo2k** [comment]
Here's a copy & pasteable example to reproduce the error in NodeJS:

```javascript
const
Iota = require('iota.lib.js'),
curl = require('curl.lib.js');

const
iota = new Iota({
  provider: 'http://5.9.118.112:14265/',
  sandbox:  false,
  token:    false
});

curl.overrideAttachToTangle(iota.api);

const
privateSeed = '9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9TEST9',
depth = 8,
weight = 14,
transactions = [ { address: privateSeed, value: 0, tag: 'SOMETHINGSPECIAL', message: 'BCCDADTCEAVCFDTCTCBDEATCVCVCGDEAPCBDSCEAGDDDPCADSA' } ];

iota.api.getNodeInfo((err, info) => { // check if synced
  if(err) {
    console.error('Error checking if node needs to be synced (%s).', err.message);
    return;
  }

  const
  isNodeUnsynced =
    info.latestMilestone == privateSeed ||
    info.latestSolidSubtangleMilestone == privateSeed ||
    info.latestSolidSubtangleMilestoneIndex < info.latestMilestoneIndex,
  isNodeSynced = !isNodeUnsynced;

  if(isNodeUnsynced) return console.error('Provider node is not synced.');

  console.log('Provider is synced, sending transaction..');

  iota.api.sendTransfer(privateSeed, depth, weight, transactions, (err, response) => {
    if(err) {
      return console.error('Error while sending transfer (%s).', err.message); // error gets thrown here:

      /*
      TypeError: Cannot read property 'context' of undefined
          at Object.search (~/node_modules/curl.lib.js/src/pearldiver.js:44:15)
          at pow (~/node_modules/curl.lib.js/src/curl.lib.js:19:31)
          at ~/node_modules/curl.lib.js/src/curl.lib.js:59:9
          at doWork (~/node_modules/curl.lib.js/src/curl.lib.js:52:14)
          at doNext (~/node_modules/curl.lib.js/src/curl.lib.js:69:9)
          at api.attachToTangle (~/node_modules/curl.lib.js/src/curl.lib.js:82:5)
          at ~/node_modules/iota.lib.js/lib/api/api.js:527:14
          at makeRequest.prepareResult (~/node_modules/iota.lib.js/lib/utils/makeRequest.js:313:12)
          at exports.XMLHttpRequest.request.onreadystatechange (~/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
          at exports.XMLHttpRequest.dispatchEvent (~/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      */
    }

    console.log('Sent:', response);
  });
});
```

**Comment by kryo2k** [comment]
Found out I was missing a call to `curl.init()`. Now I added it (after overrideAttachToTangle), I immediately get error:

```
ReferenceError: document is not defined
    at module.exports (~/node_modules/curl.lib.js/src/WebGL/initGL.js:2:16)
    at Object.WebGLWorker [as worker] (~/node_modules/curl.lib.js/src/WebGL/index.js:83:15)
    at Object.PearlDiverInstance [as instance] (~/node_modules/curl.lib.js/src/pearldiver.js:28:30)
    at Object.init (~/node_modules/curl.lib.js/src/curl.lib.js:88:29)
```

In InitGL file, it is trying to execute `canvas = document.createElement('canvas');`. This won't work in nodejs, unless I have some global shim (yuck!). Am I doing something wrong? Any way to use Node-WebGL package?

**Comment by munawarb** [comment]
Hi @kryo2k, did you end up solving this issue?

What' I've tried is using headless GL (npm install gl) and modifying initGL.js to get the webGLContext from headlessGl. But that context returns null. Did you ever manage to get PoW working, server side?
